from .commanddevice import CommandDevice

class CommandADS1115(CommandDevice):
    def __init__(self): ...
    def get_level(self) -> int: ...
    def handle_level_command(self, *arg): ...
    def handle_initialize(self, *arg): ...
    def handle_set_gain(self, *arg): ...
    def handle_set_channel(self, *arg): ...
    def set_gain(self, gain: int) -> int: ...
    def set_channel(self, channel: int) -> int: ...
